-- Phase A baseline schema: auth (users) + borrower onboarding/KYC.
-- IDENTITY columns (SQL-standard) instead of BIGSERIAL so this file runs
-- unchanged against both Postgres (main) and H2 in MODE=PostgreSQL (tests).

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role          VARCHAR(20)  NOT NULL,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_users_email UNIQUE (email)
);

CREATE TABLE borrowers (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name      VARCHAR(150)   NOT NULL,
    phone          VARCHAR(20)    NOT NULL,
    email          VARCHAR(255)   NOT NULL,
    dob            DATE           NOT NULL,
    monthly_income NUMERIC(12, 2) NOT NULL,
    kyc_level      VARCHAR(10)    NOT NULL DEFAULT 'NONE',
    is_active      BOOLEAN        NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_borrowers_email UNIQUE (email)
);

CREATE TABLE kyc_records (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    borrower_id      BIGINT      NOT NULL,
    pan_number       VARCHAR(10),
    aadhaar_number   VARCHAR(12),
    pan_verified     BOOLEAN     NOT NULL DEFAULT FALSE,
    aadhaar_verified BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at       TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_kyc_records_borrower_id UNIQUE (borrower_id),
    CONSTRAINT uq_kyc_records_pan_number UNIQUE (pan_number),
    CONSTRAINT uq_kyc_records_aadhaar_number UNIQUE (aadhaar_number),
    CONSTRAINT fk_kyc_records_borrower FOREIGN KEY (borrower_id) REFERENCES borrowers (id)
);

CREATE TABLE otp_verifications (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    borrower_id   BIGINT       NOT NULL,
    document_type VARCHAR(10)  NOT NULL,
    otp_code      VARCHAR(10)  NOT NULL,
    expires_at    TIMESTAMP    NOT NULL,
    verified      BOOLEAN      NOT NULL DEFAULT FALSE,
    attempts      INT          NOT NULL DEFAULT 0,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_otp_verifications_borrower FOREIGN KEY (borrower_id) REFERENCES borrowers (id)
);

CREATE INDEX idx_otp_verifications_borrower_doctype
    ON otp_verifications (borrower_id, document_type);
