-- Phase B: loan products (admin-configured rule engine inputs) and loan applications.

CREATE TABLE loan_products (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              VARCHAR(150)   NOT NULL,
    min_principal     NUMERIC(14, 2) NOT NULL,
    max_principal     NUMERIC(14, 2) NOT NULL,
    min_tenure_months INT            NOT NULL,
    max_tenure_months INT            NOT NULL,
    interest_rate     NUMERIC(5, 2)  NOT NULL,
    penalty_rate      NUMERIC(5, 2)  NOT NULL,
    min_kyc_level     VARCHAR(10)    NOT NULL,
    is_active         BOOLEAN        NOT NULL DEFAULT TRUE,
    created_at        TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE loan_applications (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    borrower_id             BIGINT         NOT NULL,
    product_id              BIGINT         NOT NULL,
    requested_amount        NUMERIC(14, 2) NOT NULL,
    requested_tenure_months INT            NOT NULL,
    status                  VARCHAR(10)    NOT NULL DEFAULT 'PENDING',
    rejection_reason        VARCHAR(500),
    version                 BIGINT         NOT NULL DEFAULT 0,
    created_at              TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_loan_applications_borrower FOREIGN KEY (borrower_id) REFERENCES borrowers (id),
    CONSTRAINT fk_loan_applications_product FOREIGN KEY (product_id) REFERENCES loan_products (id)
);

CREATE INDEX idx_loan_applications_borrower ON loan_applications (borrower_id);
CREATE INDEX idx_loan_applications_product ON loan_applications (product_id);
