-- Phase C: loans (frozen agreement snapshot at approval) and their installment schedules.

CREATE TABLE loans (
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    borrower_id                BIGINT         NOT NULL,
    application_id             BIGINT         NOT NULL,
    principal_amount           NUMERIC(14, 2) NOT NULL,
    interest_rate              NUMERIC(5, 2)  NOT NULL,
    tenure_months              INT            NOT NULL,
    emi_amount                 NUMERIC(14, 2) NOT NULL,
    total_payable              NUMERIC(14, 2) NOT NULL,
    total_paid                 NUMERIC(14, 2) NOT NULL DEFAULT 0,
    status                     VARCHAR(20)    NOT NULL DEFAULT 'AGREEMENT_PENDING',
    agreement_snapshot         TEXT           NOT NULL,
    agreement_acknowledged_at  TIMESTAMP,
    disbursed_at               TIMESTAMP,
    version                    BIGINT         NOT NULL DEFAULT 0,
    created_at                 TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                 TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_loans_application_id UNIQUE (application_id),
    CONSTRAINT fk_loans_borrower FOREIGN KEY (borrower_id) REFERENCES borrowers (id),
    CONSTRAINT fk_loans_application FOREIGN KEY (application_id) REFERENCES loan_applications (id)
);

CREATE TABLE installments (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loan_id         BIGINT         NOT NULL,
    installment_no  INT            NOT NULL,
    due_date        DATE           NOT NULL,
    emi_amount      NUMERIC(14, 2) NOT NULL,
    penalty_amount  NUMERIC(14, 2) NOT NULL DEFAULT 0,
    total_due       NUMERIC(14, 2) NOT NULL,
    amount_paid     NUMERIC(14, 2) NOT NULL DEFAULT 0,
    status          VARCHAR(10)    NOT NULL DEFAULT 'PENDING',
    penalty_applied BOOLEAN        NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_installments_loan_installment_no UNIQUE (loan_id, installment_no),
    CONSTRAINT fk_installments_loan FOREIGN KEY (loan_id) REFERENCES loans (id)
);

CREATE INDEX idx_installments_loan ON installments (loan_id);
