CREATE TABLE repayments (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loan_id           BIGINT         NOT NULL,
    amount            NUMERIC(14, 2) NOT NULL,
    payment_reference VARCHAR(100)   NOT NULL,
    payment_mode      VARCHAR(30)    NOT NULL,
    balance_after     NUMERIC(14, 2) NOT NULL,
    paid_at           TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_repayments_payment_reference UNIQUE (payment_reference),
    CONSTRAINT fk_repayments_loan FOREIGN KEY (loan_id) REFERENCES loans (id)
);

CREATE INDEX idx_repayments_loan ON repayments (loan_id);
